### ISSUE TITLE
Workflow::NoTransitionAllowed: There is no event approve defined for the pending state

### ISSUE THREAD

**Issue by ziweizhou** [geekq/workflow#149]
I have following code, 

```
include Workflow
  workflow do
    state :pending do
      event :approve, :transitions_to => :approved, :if => :all_approved?
      event :reject, :transitions_to => :rejected
      event :cancel, :transitions_to => :cancelled
    end
    state :approved do
      event :pay, :transitions_to => :paid
      event :book, :transitions_to => :booked
    end
    state :booked
    state :paid
    state :cancelled
    state :approved
    state :rejected

  end
```

when i do `task.approve!` I got following error. 

```
Workflow::NoTransitionAllowed: There is no event approve defined for the pending state
    from /Users/ziweizhou/Dropbox/Development/rails/test_ror/vendor/bundle/ruby/2.1.0/bundler/gems/workflow-403a9e44bf49/lib/workflow.rb:98:in `process_event!'
    from /Users/ziweizhou/Dropbox/Development/rails/test_ror/vendor/bundle/ruby/2.1.0/bundler/gems/workflow-403a9e44bf49/lib/workflow.rb:64:in `block (4 levels) in assign_workflow'
    from (irb):2
```

Any idea why?

**Comment by bytenel** [comment]
+1

**Comment by deerawan** [comment]
+1

**Comment by kwent** [comment]
+1

**Comment by timbica** [comment]
+1 : anyone out there?

**Comment by dustineichler** [comment]
I'm able to reproduce this error by doing the following. Maybe related.

Context - As a User, I want to update my Comment `state` using an API. 

```ruby
  workflow do
    state :new do
      event :submit, :transitions_to => :awaiting_review
      event :reject, :transitions_to => :rejected
    end
    state :awaiting_review do
      event :accept, :transitions_to => :approved
      event :reject, :transitions_to => :rejected
    end
    state :approved
    state :rejected
  end

  def workflow_event=(value)
    if self.class.method_defined?("#{value}!".to_sym)
      if self.send("#{value}!".to_sym)
        self.send("#{value}!".to_sym)
      else
        errors.add(:workflow_state, "Workflow State cannot transition from #{current_state.name} to #{value}.")
      end
    else
      errors.add(:workflow_state, "Workflow State of #{value} is not valid.")
    end
  end
```

Console

```ruby
[5] pry(main)> comment = Comment.create(...params...)
[5] pry(main)> comment.workflow_event = "submit"
```

`Workflow::NoTransitionAllowed: There is no event submit defined for the awaiting_review state`

**Comment by dustineichler** [comment]
And actually, I was able to deal with `Workflow::NoTransitionAllowed` at least initially by doing the following. Still looking into this.

```ruby
Thread.new do
  self.send("#{value}!".to_sym)
end
```
